/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import strapiAppVersion from "@palmabit/strapi-app-version/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import emailDesigner from "strapi-plugin-email-designer/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor5: ckeditor5,
    "strapi-app-version": strapiAppVersion,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "email-designer": emailDesigner,
    navigation: navigation,
  },
});
